/**
 * Schema Knowledge Graph Types
 * 
 * Defines the data structures for the schema-aware knowledge graph
 * that tracks dependencies between artifact fields for surgical refinement.
 */

/**
 * Represents a node in the schema knowledge graph
 * A node is a specific field or element within an artifact
 */
export interface SchemaNode {
  /** Unique identifier: "artifactType.schemaPath" e.g., "arch_design.apis[0]" */
  id: string;
  
  /** The artifact type this node belongs to */
  artifactType: string;
  
  /** The path within the artifact schema */
  schemaPath: string;
  
  /** The value at this path (for reference matching) */
  value: any;
  
  /** Type of the value */
  valueType: 'string' | 'number' | 'boolean' | 'object' | 'array';
  
  /** Metadata about this node */
  metadata: {
    /** Whether this is an array item */
    isArrayItem: boolean;
    
    /** If array item, the index */
    arrayIndex?: number;
    
    /** If has a name/id field, what is it */
    identifier?: string;
    
    /** Description from schema */
    description?: string;
  };
}

/**
 * Represents a directed edge in the knowledge graph
 * Shows that one node references/depends on another
 */
export interface SchemaEdge {
  /** Source node ID (the dependent) */
  from: string;
  
  /** Target node ID (the dependency) */
  to: string;
  
  /** Type of relationship */
  type: EdgeType;
  
  /** Confidence score (0-1) for fuzzy matches */
  confidence: number;
  
  /** How the reference was detected */
  detectionMethod: 'exact' | 'fuzzy' | 'semantic' | 'explicit';
  
  /** Context of the reference (e.g., the text that matched) */
  context?: string;
}

/**
 * Types of dependency relationships
 */
export type EdgeType = 
  | 'references'      // Direct reference to a value
  | 'implements'      // Implements a specification
  | 'uses'            // Uses a component/service
  | 'tests'           // Tests a feature
  | 'configures'      // Configures a service
  | 'extends'         // Extends functionality
  | 'depends_on';     // General dependency

/**
 * Query result for dependency lookups
 */
export interface DependencyQueryResult {
  /** The node that was queried */
  sourceNode: SchemaNode;
  
  /** Direct dependents (nodes that reference this one) */
  directDependents: SchemaNode[];
  
  /** Transitive dependents (dependents of dependents) */
  transitiveDependents: SchemaNode[];
  
  /** Edges showing the relationships */
  edges: SchemaEdge[];
  
  /** Grouped by artifact type for easy processing */
  groupedByArtifact: Record<string, SchemaNode[]>;
}

/**
 * A refinement plan generated by the knowledge graph
 */
export interface RefinementPlan {
  /** The original user intent */
  originalIntent: string;
  
  /** The target node being modified */
  targetNode: SchemaNode;
  
  /** New value for the target */
  newValue: any;
  
  /** Surgical updates needed for each affected artifact */
  updates: SurgicalUpdate[];
  
  /** Artifacts that don't need updates (for logging) */
  unaffectedArtifacts: string[];
  
  /** Estimated impact score (0-1) */
  impactScore: number;
}

/**
 * A single surgical update operation
 */
export interface SurgicalUpdate {
  /** Target artifact type */
  artifactType: string;
  
  /** Specific schema paths to update */
  targetPaths: string[];
  
  /** The instruction for the agent */
  instruction: string;
  
  /** Context from upstream dependencies */
  context: {
    /** What changed upstream */
    upstreamChange: string;
    
    /** Why this artifact needs updating */
    reason: string;
    
    /** Specific values to reference */
    referenceValues?: Record<string, any>;
  };
  
  /** Priority for ordering updates */
  priority: 'critical' | 'high' | 'medium' | 'low';
  
  /** Dependencies that must be updated first */
  dependsOn: string[];
}

/**
 * Configuration for the knowledge graph
 */
export interface KnowledgeGraphConfig {
  /** Minimum confidence for fuzzy matches */
  minConfidence: number;
  
  /** Maximum depth for transitive dependency queries */
  maxDepth: number;
  
  /** Whether to enable semantic matching (slower but more accurate) */
  enableSemanticMatching: boolean;
  
  /** Fields to ignore when building the graph */
  ignoredFields: string[];
  
  /** Fields that are identifiers (used for stable references) */
  identifierFields: string[];
}

/**
 * Default configuration
 */
export const DEFAULT_KG_CONFIG: KnowledgeGraphConfig = {
  minConfidence: 0.7,
  maxDepth: 5,
  enableSemanticMatching: true,
  ignoredFields: ['summary', 'description', 'design_doc', 'implementation_plan'],
  identifierFields: ['id', 'name', 'path', 'title', 'key'],
};

/**
 * Artifact dependency map - static relationships between artifact types
 */
export const ARTIFACT_DEPENDENCY_MAP: Record<string, string[]> = {
  pm_spec: [],
  arch_design: ['pm_spec'],
  security_architecture: ['arch_design', 'pm_spec'],
  devops_infrastructure: ['arch_design', 'pm_spec', 'security_architecture'],
  ui_design: ['arch_design', 'pm_spec'],
  engineer_impl: ['arch_design', 'pm_spec', 'ui_design', 'security_architecture', 'devops_infrastructure'],
  qa_verification: ['engineer_impl', 'arch_design', 'pm_spec', 'ui_design', 'security_architecture', 'devops_infrastructure'],
};

/**
 * Result of building the knowledge graph
 */
export interface GraphBuildResult {
  /** Number of nodes created */
  nodeCount: number;
  
  /** Number of edges created */
  edgeCount: number;
  
  /** Artifacts processed */
  artifactsProcessed: string[];
  
  /** Any warnings during build */
  warnings: string[];
  
  /** Build timestamp */
  timestamp: string;
  
  /** LLM calls made during build */
  llmCalls?: number;
  
  /** Total tokens used for reference detection */
  tokensUsed?: number;
}
