import type { Diagram } from "@/types/diagram"

export class DeploymentGenerator {
  private diagram: Diagram
  private artifacts: any

  constructor(diagram: Diagram) {
    this.diagram = diagram
    this.artifacts = diagram.metadata?.metasop_artifacts || {}
  }

  /**
   * Generate deployment guide
   */
  generateDeploymentGuide(): string {
    const archContent = this.artifacts.arch_design?.content || {}
    const hasDatabase = !!archContent.database_schema

    let guide = `# Deployment Guide

## ${this.diagram.title}

This guide provides step-by-step instructions for deploying the application.

---

## Prerequisites

- Node.js 20.x or higher
- npm or yarn package manager
${hasDatabase ? "- PostgreSQL 14+ or compatible database\n- Database credentials" : ""}
- Git
- Docker (optional, for containerized deployment)

---

## Environment Setup

### 1. Clone the Repository

\`\`\`bash
git clone <repository-url>
cd ${this.diagram.title.toLowerCase().replace(/\s+/g, "-")}
\`\`\`

### 2. Install Dependencies

\`\`\`bash
npm install
\`\`\`

### 3. Configure Environment Variables

Copy the example environment file and configure it:

\`\`\`bash
cp .env.example .env
\`\`\`

Edit \`.env\` and set the following variables:

\`\`\`env
NODE_ENV=production
PORT=3000
${hasDatabase ? `DATABASE_URL=postgresql://user:password@localhost:5432/dbname` : ""}
\`\`\`

---

## Database Setup

${hasDatabase ? this.generateDatabaseSetup() : "No database configuration required."}

---

## Build the Application

\`\`\`bash
npm run build
\`\`\`

This will:
- Compile TypeScript
- Optimize assets
- Generate production-ready build

---

## Local Development

\`\`\`bash
npm run dev
\`\`\`

The application will be available at \`http://localhost:3000\`

---

## Production Deployment

### Option 1: Docker Deployment

\`\`\`bash
# Build Docker image
docker build -t ${this.diagram.title.toLowerCase().replace(/\s+/g, "-")} .

# Run container
docker run -p 3000:3000 --env-file .env ${this.diagram.title.toLowerCase().replace(/\s+/g, "-")}
\`\`\`

### Option 2: Docker Compose

\`\`\`bash
docker-compose up -d
\`\`\`

### Option 3: Platform Deployment

#### Vercel

1. Install Vercel CLI: \`npm i -g vercel\`
2. Run: \`vercel\`
3. Follow the prompts

#### Railway

1. Connect your GitHub repository
2. Railway will auto-detect and deploy
3. Add environment variables in Railway dashboard

#### AWS (EC2/ECS)

${this.generateAWSDeployment()}

---

## CI/CD Pipeline

### GitHub Actions Example

\`\`\`yaml
name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
      - run: npm test
      # Add deployment steps here
\`\`\`

---

## Health Checks

After deployment, verify the application is running:

\`\`\`bash
curl http://your-domain.com/api/health
\`\`\`

Expected response: \`{"status": "ok"}\`

---

## Monitoring

- Set up error tracking (Sentry, LogRocket, etc.)
- Configure application monitoring
- Set up uptime monitoring
- Configure log aggregation

---

## Troubleshooting

### Common Issues

1. **Port already in use**
   - Change PORT in .env file
   - Or kill the process using the port

2. **Database connection errors**
   - Verify DATABASE_URL is correct
   - Check database is running
   - Verify network connectivity

3. **Build failures**
   - Clear node_modules and reinstall
   - Check Node.js version compatibility
   - Review build logs for specific errors

---

## Rollback Procedure

If deployment fails:

1. Revert to previous version: \`git revert HEAD\`
2. Rebuild and redeploy
3. Or use platform-specific rollback features

---

## Security Checklist

- [ ] Environment variables are secure
- [ ] Database credentials are encrypted
- [ ] HTTPS is enabled
- [ ] CORS is properly configured
- [ ] Rate limiting is enabled
- [ ] Authentication is implemented
- [ ] Dependencies are up to date
- [ ] Security headers are configured

---

Generated by ArchitectAI - ${new Date().toLocaleString()}
`

    return guide
  }

  private generateDatabaseSetup(): string {
    return `### 1. Create Database

\`\`\`bash
createdb ${this.diagram.title.toLowerCase().replace(/\s+/g, "_")}
\`\`\`

### 2. Run Migrations

\`\`\`bash
npx prisma migrate deploy
\`\`\`

Or if using raw SQL:

\`\`\`bash
psql -d ${this.diagram.title.toLowerCase().replace(/\s+/g, "_")} -f prisma/migrations/init.sql
\`\`\`

### 3. Seed Data (Optional)

\`\`\`bash
npx prisma db seed
\`\`\`
`
  }

  private generateAWSDeployment(): string {
    return `1. **EC2 Deployment**
   - Launch EC2 instance (Ubuntu 22.04)
   - Install Node.js and PM2
   - Clone repository
   - Configure environment variables
   - Run: \`pm2 start npm --name "app" -- start\`

2. **ECS Deployment**
   - Push Docker image to ECR
   - Create ECS task definition
   - Create ECS service
   - Configure load balancer

3. **Elastic Beanstalk**
   - Install EB CLI
   - Run: \`eb init\`
   - Run: \`eb create\`
   - Configure environment variables`
  }
}

