import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { ExternalLink } from "lucide-react"

const examples = [
  {
    title: "Social Media App",
    description: "Complete architecture with authentication, posts, comments, and real-time updates",
    gradient: "from-blue-500/10 to-cyan-500/10",
    preview: {
      nodes: [
        { id: "app", label: "App", color: "primary" },
        { id: "auth", label: "Auth", color: "accent" },
        { id: "posts", label: "Posts", color: "primary" },
        { id: "comments", label: "Comments", color: "accent" },
      ],
    },
  },
  {
    title: "E-commerce Platform",
    description: "Shopping cart, payment processing, inventory management, and user profiles",
    gradient: "from-purple-500/10 to-pink-500/10",
    preview: {
      nodes: [
        { id: "store", label: "Store", color: "primary" },
        { id: "cart", label: "Cart", color: "accent" },
        { id: "payment", label: "Payment", color: "primary" },
        { id: "inventory", label: "Inventory", color: "accent" },
        { id: "security", label: "Security", color: "primary" },
        { id: "devops", label: "DevOps", color: "accent" },
      ],
    },
  },
  {
    title: "SaaS Dashboard",
    description: "Analytics, user management, settings, and subscription handling",
    gradient: "from-emerald-500/10 to-teal-500/10",
    preview: {
      nodes: [
        { id: "dashboard", label: "Dashboard", color: "primary" },
        { id: "analytics", label: "Analytics", color: "accent" },
        { id: "users", label: "Users", color: "primary" },
        { id: "settings", label: "Settings", color: "accent" },
      ],
    },
  },
]

export function Examples() {
  return (
    <section className="py-20 md:py-32 relative overflow-hidden">
      {/* Background decoration */}
      <div className="absolute inset-0 bg-linear-to-b from-transparent via-purple-500/5 to-transparent pointer-events-none" />

      <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-2xl mx-auto">
          <Badge variant="outline" className="mb-4">
            Examples
          </Badge>
          <h2 className="mt-2 text-3xl sm:text-4xl font-bold text-foreground text-balance">
            See what you can build
          </h2>
          <p className="mt-4 text-lg text-muted-foreground">
            Explore real architecture diagrams generated by our AI for popular app types.
          </p>
        </div>

        <div className="mt-16 grid md:grid-cols-3 gap-6">
          {examples.map((example, index) => (
            <Card
              key={index}
              className="group relative overflow-hidden border-border/50 hover:border-border transition-all duration-300 hover:shadow-lg hover:shadow-blue-500/10 dark:hover:shadow-blue-500/20"
            >
              {/* Gradient overlay on hover */}
              <div className={`absolute inset-0 bg-linear-to-br ${example.gradient} opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none`} />

              <CardHeader className="pb-4">
                {/* Diagram preview */}
                <div className="h-40 w-full rounded-lg bg-muted/50 border border-border/50 flex items-center justify-center mb-4 relative overflow-hidden group-hover:border-border transition-colors">
                  <div className="grid grid-cols-2 gap-2.5 p-3 w-full h-full">
                    {example.preview.nodes.map((node, nodeIndex) => (
                      <div
                        key={nodeIndex}
                        className={`rounded-md border flex items-center justify-center transition-transform duration-300 group-hover:scale-105 ${node.color === "primary"
                            ? "bg-blue-500/10 border-blue-500/30 text-blue-600 dark:text-blue-400"
                            : "bg-cyan-500/10 border-cyan-500/30 text-cyan-600 dark:text-cyan-400"
                          }`}
                      >
                        <span className="text-xs font-medium">{node.label}</span>
                      </div>
                    ))}
                  </div>
                  {/* Connection lines */}
                  <svg className="absolute inset-0 pointer-events-none">
                    <line
                      x1="25%"
                      y1="25%"
                      x2="75%"
                      y2="25%"
                      stroke="currentColor"
                      strokeWidth="1.5"
                      className="text-blue-500/20 dark:text-blue-400/20"
                    />
                    <line
                      x1="25%"
                      y1="75%"
                      x2="75%"
                      y2="75%"
                      stroke="currentColor"
                      strokeWidth="1.5"
                      className="text-cyan-500/20 dark:text-cyan-400/20"
                    />
                  </svg>
                </div>

                <h3 className="text-lg font-semibold text-foreground group-hover:text-foreground transition-colors">
                  {example.title}
                </h3>
              </CardHeader>

              <CardContent className="pt-0">
                <p className="text-sm text-muted-foreground leading-relaxed mb-4">
                  {example.description}
                </p>

                <Button
                  variant="outline"
                  size="sm"
                  className="w-full border-border hover:bg-accent hover:text-accent-foreground group-hover:border-primary group-hover:text-primary transition-colors"
                >
                  View Full Diagram
                  <ExternalLink className="ml-2 h-3.5 w-3.5" />
                </Button>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  )
}

