/**
 * Utility to export agent-generated artifacts as a structured Markdown document
 * optimized for use as context for AI coding assistants.
 */

export function generateAgentContextMarkdown(diagram: any): string {
    if (!diagram) return "";

    const artifacts = diagram.metadata?.metasop_artifacts || {};

    // Correct keys according to agent implementations
    const pm = artifacts.pm_spec?.content || {};
    const arch = artifacts.arch_design?.content || {};
    const ui = artifacts.ui_design?.content || {};
    const eng = artifacts.engineer_impl?.content || {};
    const sec = artifacts.security_architecture?.content || {};
    const devops = artifacts.devops_infrastructure?.content || {};

    let md = `# ${diagram.title || pm.title || "Project Architecture Blueprint"}\n\n`;
    md += `${diagram.description || pm.summary || ""}\n\n`;
    md += `> **MetaSop Context**: This document contains the full architectural and engineering specifications for the project, generated by the MetaSop multi-agent orchestration platform. Use this as high-fidelity context for implementation.\n\n`;

    md += `---` + `\n\n`;

    // 1. Product Specification & Strategy
    md += `## 1. Product Specification & Strategy\n\n`;
    md += `### Summary\n${pm.summary || "N/A"}\n\n`;
    md += `### Description\n${pm.description || "N/A"}\n\n`;
    md += `### Core User Flows\n`;
    if (pm.user_flows && Array.isArray(pm.user_flows)) {
        pm.user_flows.forEach((flow: any) => {
            md += `- **${flow.name}**: ${flow.description}\n`;
        });
    } else if (pm.user_stories && Array.isArray(pm.user_stories)) {
        pm.user_stories.forEach((story: any) => {
            md += `- **${story.title}**: ${story.description || story.story}\n`;
        });
    } else {
        md += "N/A\n";
    }
    md += `\n`;

    // 2. Architectural Design
    md += `## 2. Architectural Design\n\n`;
    md += `### System Documentation\n${arch.design_doc || arch.description || "N/A"}\n\n`;

    md += `### Core APIs\n`;
    if (arch.apis && Array.isArray(arch.apis)) {
        md += `| Method | Path | Description | Auth |\n`;
        md += `|--------|------|-------------|------|\n`;
        arch.apis.forEach((api: any) => {
            md += `| ${api.method} | \`${api.path}\` | ${api.description} | ${api.auth_required ? "Yes" : "No"} |\n`;
        });
    } else {
        md += "N/A\n";
    }
    md += `\n`;

    md += `### Database Schema\n`;
    if (arch.database_schema && arch.database_schema.tables && Array.isArray(arch.database_schema.tables)) {
        arch.database_schema.tables.forEach((table: any) => {
            md += `#### Table: \`${table.name}\`\n`;
            md += `${table.description || ""}\n\n`;
            md += `| Column | Type | Constraints |\n`;
            md += `|--------|------|-------------|\n`;
            if (table.columns && Array.isArray(table.columns)) {
                table.columns.forEach((col: any) => {
                    md += `| ${col.name} | ${col.type} | ${col.constraints?.join(", ") || ""} |\n`;
                });
            }
            md += `\n`;
        });
    } else {
        md += "N/A\n";
    }
    md += `\n`;

    // 3. UI & Design System
    md += `## 3. UI & Design System\n\n`;
    md += `### Design Strategy\n${ui.summary || "N/A"}\n\n`;

    if (ui.design_tokens) {
        md += `### Design Tokens\n`;
        const tokens = ui.design_tokens;
        if (tokens.colors) {
            md += `- **Primary Color**: ${tokens.colors.primary || "N/A"}\n`;
            md += `- **Secondary Color**: ${tokens.colors.secondary || "N/A"}\n`;
            md += `- **Background**: ${tokens.colors.background || "N/A"}\n`;
        } else {
            md += `- **Primary Color**: ${tokens.primary_color || "N/A"}\n`;
            md += `- **Secondary Color**: ${tokens.secondary_color || "N/A"}\n`;
        }
        if (tokens.typography) {
            md += `- **Font Family**: ${tokens.typography.fontFamily || tokens.typography.headingFont || "N/A"}\n`;
        }
        md += `\n`;
    }

    md += `### Component Hierarchy\n`;
    if (ui.component_hierarchy && ui.component_hierarchy.children) {
        ui.component_hierarchy.children.forEach((comp: any) => {
            md += `- **${comp.name}**: ${comp.description || ""}\n`;
        });
    } else if (ui.component_specs && Array.isArray(ui.component_specs)) {
        ui.component_specs.forEach((comp: any) => {
            md += `- **${comp.name}**: ${comp.description || ""}\n`;
        });
    } else {
        md += "N/A\n";
    }
    md += `\n`;

    if (ui.website_layout && Array.isArray(ui.website_layout)) {
        md += `### Website Layout Pages\n`;
        ui.website_layout.forEach((page: any) => {
            md += `- **${page.name}** (\`${page.route}\`): ${page.sections?.join(", ") || ""}\n`;
        });
        md += `\n`;
    }

    // 4. Engineering Blueprint
    md += `## 4. Engineering Blueprint\n\n`;

    const stack = arch.technology_stack || {};
    const techItems = Object.values(stack).flat().filter(Boolean);
    md += `### Tech Stack\n${techItems.length > 0 ? techItems.join(", ") : "N/A"}\n\n`;

    md += `### Recommended File Structure\n`;
    md += "```text\n";
    function renderTree(node: any, indent: string = "") {
        if (!node) return "";
        let treeStr = `${indent}${node.name}${node.type === "directory" ? "/" : ""}\n`;
        if (node.children && Array.isArray(node.children)) {
            node.children.forEach((child: any) => {
                treeStr += renderTree(child, indent + "  ");
            });
        }
        return treeStr;
    }
    if (eng.file_structure) {
        md += renderTree(eng.file_structure);
    } else {
        md += "N/A\n";
    }
    md += "```\n\n";

    md += `### Implementation Roadmap\n`;
    if (eng.implementation_plan) {
        md += `${eng.implementation_plan}\n`;
    } else if (eng.phases && Array.isArray(eng.phases)) {
        eng.phases.forEach((phase: any) => {
            md += `#### Phase ${phase.order}: ${phase.name}\n`;
            md += `${phase.description}\n`;
            if (phase.tasks && Array.isArray(phase.tasks)) {
                phase.tasks.forEach((task: any) => {
                    md += `- [ ] ${task.title}: ${task.description}\n`;
                });
            }
            md += `\n`;
        });
    } else {
        md += "N/A\n";
    }
    md += `\n`;

    // 5. Security & Compliance
    md += `## 5. Security Architecture\n\n`;
    md += `### Security Model\n${sec.summary || sec.description || "N/A"}\n\n`;

    md += `### Threat Model Highlights\n`;
    if (sec.threats && Array.isArray(sec.threats)) {
        sec.threats.forEach((t: any) => {
            md += `- **${t.threat}** (${t.severity}): ${t.mitigation}\n`;
        });
    } else if (sec.threat_model && Array.isArray(sec.threat_model)) {
        sec.threat_model.forEach((t: any) => {
            md += `- **${t.threat}** (${t.severity}): ${t.mitigation}\n`;
        });
    } else {
        md += "N/A\n";
    }
    md += `\n`;

    // 6. Infrastructure & Operations
    md += `## 6. Infrastructure & DevOps\n\n`;
    md += `### Cloud Provider: ${devops.cloud_provider || "N/A"}\n\n`;

    md += `### Infrastructure Components\n`;
    if (devops.services && Array.isArray(devops.services)) {
        devops.services.forEach((s: any) => {
            md += `- **${s.name}** (${s.type}): ${s.description}\n`;
        });
    } else {
        md += "N/A\n";
    }
    md += `\n`;

    md += `### Deployment Strategy\n${devops.rollback_strategy || "N/A"}\n\n`;

    md += `---` + `\n`;
    md += `*Generated by MetaSop - Your AI Architectural Partner*`;

    return md;
}
